## CIND830 - Python Programming for Data Science  
### Assignment 2 (10% of the final grade)
### Due on March 15, 2021 11:59 PM

*****
This is a Jupyter Notebook document that extends a simple formatting syntax for authoring HTML and PDF.
Review [this](https://jupyter-notebook.readthedocs.io/en/stable/notebook.html) website for more details on using Juputer Notebook.

Use the JupyterHub server on the Google Cloud Platform, provided by your designated instructor, for this assignment. Ensure using Python 3.7.6 release then complete the assignment by inserting your Python code wherever seeing the string "#INSERT YOUR ANSWER HERE."

When you click the `File` button, from the top navigation bar, then select `Export Notebook As ...`,
a document (PDF or HTML format) will be generated that includes
 both the assignment content and the output of any embedded Python code chunks.

Using [these](https://www.ryerson.ca/courses/students/tutorials/assignments/) guidelines,
submit **both** the IPYNB and the exported file (PDF or HTML).
Failing to submit both files will be subject to mark deduction.

*****

### Question 1 **[50 pts]**:

**a)** **[15 pts]** Define a function called `isSymmetrical` that takes a string value as a parameter and returns `TRUE` if the given string is Symmetrical. A string is said to be symmetrical if the reverse of the string is the same as string. For example, “madam” is symmetrical, but “water” is not symmetrical.

In [1]:
def isSymmetrical(var1):
    if var1== var1[-1::-1]:
        return True
    else:
        return False 
    
var= input("Please enter your word:")

if isSymmetrical(var): 
    print("String is symmentrical")
else:
    print("String is not symmentrical")


Please enter your word:car
String is not symmentrical


**b)** **[5 pts]** Modify the `isSymmetrical` function you created in Q1.a to take any type of data as an input and return `TRUE` if the input is symmetrical. For example, "12321" is symmetrical, but "12345" is not symmetrical.

In [2]:
def isSymmetrical(var1):
    var1=str(var1)
    if var1== var1[-1::-1]:
        return True
    else:
        return False 


**c)** **[10 pts]** Define a function called `isSymmetricalVec` that calls `isSymmetrical` function you updated in Q1.b to take a list of elements and return their results in a list.  For example, given \["1441", "Apple", "radar", "232", "plane"\] the function returns \[`TRUE`, `FALSE`, `TRUE`, `TRUE`, `FALSE`\]

In [3]:
def isSymmetricalVec(values):
    output=[]
    for value in values:
        if isSymmetrical(value):
            output.append("TRUE")
        else:
            output.append("FALSE")
    return output
isSymmetricalVec(["1441", "Apple", "radar", "232", "plane"])


['TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE']

**d)** **[10 pts]** Define a function called `isSymmetricalDict` by modifying the function you created in Q1.c to return the results in a dictionary with their corresponding input elements. \
For example, given \["1441", "Apple", "radar", "232", "plane"\] the function returns {"1441": `TRUE`, "Apple": `FALSE`, "radar": `TRUE`, "232": `TRUE`, "plane": `FALSE`\}

In [4]:
def isSymmetricalDict(values):
    output={}
    for value in values:
        if isSymmetrical(value):
            output[value]= True
        else:
            output[value]= False
    return output
isSymmetricalDict(["1441", "Apple", "radar", "232", "plane"])

{'1441': True, '232': True, 'Apple': False, 'plane': False, 'radar': True}

**e)** **[10 pts]** Define a function called `isSymmetricalTuple` by modifying the function you created in Q1.d to traverse the values of the returned dictionary **in reverse order** and return the dictionary keys that has a **`TRUE`** value as a tuple.  For example, given \["1441", "Apple", "radar", "232", "plane"\] the function returns ("232", "radar","1441").

In [5]:
def isSymmetricalTuple(values):
    output=[]
    items=list(values.items()) #converted dict into list of tuples
    for key,value in items[-1::-1]: #reversed 
        if value == True: #only if true then return it 
            output.append(key)

    return tuple(output) #converted to tuple if true from before

isSymmetricalTuple(isSymmetricalDict(["1441", "Apple", "radar", "232", "plane"]))

('232', 'radar', '1441')

*****



### Question 2 **[80 pts]** :



**a)** **[15 pts]** Define a function called `minSubStr` that takes two string arguments ( S and T ), and returns `TRUE` if the characters of *T* exist in *S*, else returns `FALSE`. For example: given `S = 'xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx'` and `T = "ABC"`, returns `TRUE` (`T = "ABCD"`, returns `FALSE)`


In [6]:
def minSubStr(S,T):
    for i in T:
        if i not in S:
            return False 
    return True     


**b)** **[15 pts]** Modify your `minSubStr` function defined in Q2.a to return the first possible substring (traversing from left) containing all the elements of `T`. For example: given `S = 'xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx'` and `T = "ABC"`, returns **`"BxxAxxC"`**

In [7]:
def minSubStr(S,T):
    substr=[]
    
    for i in T:
        if i not in S:
            return -1
        substr.append(S.index(i)) #substr index element of each matching
    startindex=min(substr)    
    stopindex=max(substr) +1
    return S[startindex:stopindex]

minSubStr('xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx','ABC')

'BxxAxxC'

**c)** **[20 pts]** Modify your `minSubStr` function defined in Q2.b to return the shortest substring containing all the elements of T. For example: given `S = 'xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx'` and `T = "ABC"`, returns **`"AxCxB"`**


In [8]:
def minSubStr(S,T):
    substr=[]
    
    for i in T:
        if i not in S:
            return -1
        substr.append(S.index(i)) #substr index element of each matching
    startindex=min(substr)    
    stopindex=max(substr) +1
    return S[startindex:stopindex]

minSubStr('xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx','ABC')

'BxxAxxC'

**d)** **[30 pts]** modify your `minSubStr` function defined in Q2.c to return the shortest substring containing all the elements of T in order. For example: given `S = 'xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx'` and `T = "ABC"`, returns **`"AxxBxC"`**

In [9]:
def minSubstr(S,T):
    t_dict = {}
    for k in T:
        t_dict[k] = []

    for k in T:
        for idx, value in enumerate(S):
            if k == value:
                t_dict[k].append(idx)
    first = t_dict[T[0]]
    combinations = []
    for i in t_dict[T[0]]:
        for j in t_dict[T[1]]:
            if i < j and [i,j] not in combinations:
                combinations.append([i,j])
    if len(T) > 2:
        for char in T[2:]:
            for index, combination in enumerate(combinations):
                for idx in t_dict[char]:
                    if idx > combination[-1] and len(combination) != len(T):
                        combinations[index].append(idx)
    shortest_substring = ''
    for combination in combinations:
        if len(shortest_substring) == 0:
            shortest_substring = S[combination[0]:combination[-1]+1]
        elif len(S[combination[0]:combination[-1]+1]) < len(shortest_substring):
            shortest_substring = S[combination[0]:combination[-1]+1]
            
    
    return shortest_substring

#test line print(minSubstr('xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx', 'ABC'))
#test line print(minSubstr('ABC', 'ABC'))
#test line print(minSubstr('AxBxCxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx', 'ABC'))

*****

### Question 3 **[30 pts]**:


**a)** Complete the given code to define three classes, Shape, Oval and Circle. 
- Shape will be the parent class of Oval and Circle. 
- Randomly create ten objects from Oval and Circle classes using the ``for`` loop given below
- Your code should produce correct number of Shapes, Circle and Oval objects. The count of objects should be calculated within the class definitions. 
  - Example output (note that since it is random every time it will be a different number of shapes) \\
  There are  10 random shape objects ['Circle', 'Circle', 'Circle', 'Circle', 'Oval', 'Circle', 'Oval', 'Oval', 'Circle', 'Circle'] \\
	 3 of them are ovals \\
	 7 of them are cirlces \\


In [10]:
# Define Shape class
class Shape(object):#create a class variable that is commonly shared among shapes not by init method, inside class outside init
    shapecount = 0
    def __init__(self):
        Shape.shapecount +=1 #increment the count shape
    
# Define Oval class
class Oval(Shape):
    ovalcount = 0
    def __init__(self):
        super().__init__()
        Oval.ovalcount +=1
    
# Define Circle class
class Circle(Shape):
    circlecount = 0
    def __init__(self):
        super().__init__()
        Circle.circlecount +=1
    

# Run the following lines of code 

from random import choice
list_of_shapes = [choice(['Circle', 'Oval']) for x in range(10)]
for shape in list_of_shapes:
    if shape == 'Oval':
        Obj = Oval()
    else:
        Obj = Circle()
# Print the list_of_shapes
print(list_of_shapes)
# Print number of shape objects
print("Number of shape objects are", Shape.shapecount)
# Print number of Oval objects
print(Oval.ovalcount, "of them are ovals ")
# Print number of circle objects
print(Circle.circlecount, "of them are circles")

['Oval', 'Circle', 'Circle', 'Oval', 'Circle', 'Oval', 'Circle', 'Circle', 'Circle', 'Circle']
Number of shape objects are 10
3 of them are ovals 
7 of them are circles


#### This is the end of assignment 2